---
# Source: promotion/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-project-workflows-gitops-pr-29
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: test-project
  source:
    path: .gitops/deploy/helm
    repoURL: https://github.com/unbounded-tech/workflows-gitops.git
    targetRevision: renovate/unbounded-tech-workflow-simple-release-2.x
    helm:
      version: v3
      values: |
        env:
          test: true
          type: preview
          method: promotion
          event: pr
        image:
          tag: pr-29-6bb06d5608a11870e2f2b45e3289d434324b28c9
  destination:
    namespace: workflows-gitops-pr-29
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
# Source: promotion/templates/preview-resources.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: something
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: test-project
  source:
    path: .gitops/deploy/helm
    repoURL: https://github.com/unbounded-tech/something.git
    targetRevision: main
    helm:
      version: v3
  destination:
    namespace: workflows-gitops-pr-29
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
